### ISSUE TITLE
Friends System and Messaging System

### ISSUE THREAD

**Issue by JosTheDude** [smuddgge/Leaf#1]
**Planned Feature Set - Friends & Cross Server Messaging**

- Simple friending system
-> PremiumVanish/VelocityVanish/Vanish compatibility
-> Server filter (servers friends can actually been seen on) and status system (you can hide yourself as offline)
-> Toggling friend requests
-> Configurable join / leave messages
-> VelocityGUI API used for GUI???
-> Future Partying???
- Modular cross-server messaging system (/msg, /msgtoggle, /r)
-> Configurable along with friending
-> Message toggling, settings for friend-only messagings

Future partying plan set?

# Smudge Edit
From your request, i have narrowed it down to the following :3

# Cross Server Messaging
- [x] Message command
- [x] Reply command

Let me know if there are any more you would like to be added

**Comment by smuddgge** [comment]
From your request i have narrowed it down to the following :3

# Friend System
- [ ] Add friend command
- [ ] Remove friend command
- [ ] Friend info command
- [ ] Friend join / leave message

# Cross Server Messaging
- [ ] Message command
- [ ] Reply command

Let me know if there are any more you would like to be added

**Comment by smuddgge** [comment]
Moved the friends system to #4
