### ISSUE TITLE
Various Feature Requests [Makes the core feel more whole]

### ISSUE THREAD

**Issue by R00tB33rMan** [smuddgge/Leaf#26]
All of these requests are optional and to your discretion; however, I find Leaf incredibly useful for my production networks and would like to be rid of some baselevel proxy plugins that could be better implemented into Leaf.

**/hub (or /lobby command with customized aliases)**
This feature would also support multiple assigned lobbies, rather than simply one.
For instance:
- Hub-1
- Hub-2
Instead of simply sending that given user to the same lobby until it's full, load balance users and determine which lobby has the lowest number of players for sending.
Ex.: Hub-1 has 1 player, Hub-2 has 0 players: send {player} to Hub-2.
Implement command disabling for this feature, so they cannot run /hub (and aliases) in that given hub.

**Load balancing feature on user join**
Similar to the feature above, allow for a feature that automatically sends users to the lobby with the lowest amount of players. Multiple lobbies once again can be specified.

**Ping/server brand feature** [This is possible; VelocityTools contains this, as an example]
Customization of the server brand would be the perfect tool for networks wishing to hide away their software or just would be a nice bonus feature for users wanting to make things look a bit more "appetizing."
Allow for branding to contain placeholders that pulls the brand from the server, in which can be removed and put into hard text; allow for HEX + base color configuration.

**Comment by smuddgge** [comment]
Thank you for all of your feature requests. I love the ideas! I have branched them into separate issues to work on independently :3 

#27 - Join command
#28 - Events (Load balancing)
#29 - Ping/Server branding

#30 - Used to stop players from running `/hub` in the lobby servers.
I did it this way as then you can also do it for other commands, lots of customisation!

Feel free to add more ideas to the branched issues :3

**Comment by R00tB33rMan** [comment]
Will do! This all looks quite solid. Can’t wait to see what it to come!
