### ISSUE TITLE
Ping/Server brand feature

### ISSUE THREAD

**Issue by smuddgge** [smuddgge/Leaf#29]
```
[This is possible; VelocityTools contains this, as an example]
Customization of the server brand would be the perfect tool for networks wishing to hide away their software or just would be a nice bonus feature for users wanting to make things look a bit more "appetizing."
Allow for branding to contain placeholders that pulls the brand from the server, in which can be removed and put into hard text; allow for HEX + base color configuration.
```

Branching from #26

**Comment by JosTheDude** [comment]
Will make a fork and PR this in :D

**Comment by R00tB33rMan** [comment]
Hey! Any update on this? Doesn't seem a PR was unfortunately made in quite a bit.

**Comment by smuddgge** [comment]
oo that code is quite helpful. @JosTheDude Are you still working on this, or would you like me to attempt to implement it :3

**Comment by smuddgge** [comment]
Jos said they don't have enough time, I'll possible look into sometime in the future. But I have a few projects id like to do also first :3

**Comment by smuddgge** [comment]
Will be with version 3.7.0
