### ISSUE TITLE
Friends - You can send multiple requests to the same person and have multiple of the same friend

### ISSUE THREAD

**Issue by CoolDCB** [smuddgge/Leaf#43]
`Leaf Version: 3.3.0`

**Description of the Bug**
If you request to be friends with each other you can both accept the friend request

**Console Errors**
```
none
```

**Comment by smuddgge** [comment]
- Added check for if there has already been a friend request sent.
- Added a check if they are already friends.

This will be implemented with the next version, thank you for reporting :3
