### ISSUE TITLE
Ping Command

### ISSUE THREAD

**Issue by GronyRalph** [smuddgge/Leaf#58]
/ping command to check on your or other people's ping would be cool, would save me 1 plugin :)

**Comment by GronyRalph** [comment]
I said /ping or /ping player, I don't know why GitHub removed it

**Comment by smuddgge** [comment]
Oo, that would be a cool command, may have a look into on Sunday if i become free :3 What is the name of the current plugin you use for it?

**Comment by smuddgge** [comment]
Oo idea! I could see if i can add a ping placeholder, and then users could use the find command type to make a ping command. I could add this with a TPS placeholder if possible.

**Comment by GronyRalph** [comment]
> Oo idea! I could see if i can add a ping placeholder, and then users could use the find command type to make a ping command. I could add this with a TPS placeholder if possible.

:D "PingPlayer", but I only can see the ping of players that are in the same server as me, you knwp, and what's the TPS placeholder for? really curious

**Comment by smuddgge** [comment]
![Screenshot 2023-09-02 at 13 27 06](https://github.com/smuddgge/Leaf/assets/68658429/799694be-5158-4bfa-92d3-b2f32ab0589e)
ooo ping is easy xD

**Comment by GronyRalph** [comment]
:D

**Comment by smuddgge** [comment]
Added to version 3.8.0 :3 
Thank you for your feature request
