### ISSUE TITLE
Online Player Detection Appears to Not Be Working

### ISSUE THREAD

**Issue by JosTheDude** [smuddgge/Leaf#7]
Title! Video attached with bug details / representation, on latest version (1.2.4)

https://user-images.githubusercontent.com/43651265/210691347-b049bc05-e857-4711-8b50-96a8deb59c41.mp4

**Comment by smuddgge** [comment]
I believe this may have occurred because you are both `Vanishable` players (permission node `leaf.vanishable`) And as there's only one player online the plugin assumes`Vanishable` players are in vanish. Ill look into if this is the case, and maybe adding a bypass if both players are `Vanishable` :3

**Comment by smuddgge** [comment]
When the next version is ready add this to `Find` and `Message` commands :

`vanishable_players: true`

This will enable vanishable players to message other vanishable players when in vanish :3
