### ISSUE TITLE
JDA compatibility issues

### ISSUE THREAD

**Issue by Jobmaximous** [smuddgge/Leaf#76]
`Leaf Version:`
Leaf
**Description of the Bug**
Even with all discordjs features disabled, leaf causes compatibility issues with cleanstaffchat. The cleanstaffchat developer has stated the following:

so, i think it's a leaf problem and it may be solved by they
problem found: https://github.com/smuddgge/Leaf/blob/97fd322b6994dd7597a384a22ce458a5e5a8dc61/pom.xml#L117

they use the same dependency with an old version, they have to relocate it or use a newer version.

**Console Errors**
```
Paste your error here if you get any errors.
```

**Comment by smuddgge** [comment]
Hey, thank you for reporting! Im not sure why it would be my plugins dependency xD But ill update it just incase 👍 
If you get any errors i could take a look into it, also leaf has staffchat if you want to use that instead :3

Dependency bump to `5.0.0-beta.14` will be included with `4.3.0`
